language: go

go:
  - 1.9.x
  - 1.10.x
  - tip

before_install:
  - go install -race std
  - go get golang.org/x/tools/cmd/cover

install:
  - make deps

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - go: tip